### ISSUE TITLE
Problem：GetElfSymbolOffset Failed with GetElfSymbolOffset: symtab not found

### ISSUE THREAD

**Issue by hw0505** [microsoft/Cornelius#10]
When I executed this command, I got the following error. Has anyone encountered a similar problem?
`\Test.exe pseamldr.so.consts pseamldr.so libtdx.so`

error：
`[+] Creating the Cornelius VM`
`[+] Executing PSEAMLDR.INSTALL on VCPU0`
`[!] GetElfSymbolOffset Failed with GetElfSymbolOffset: symtab not found`

**Comment by JohnMcSandwich** [comment]
You must pass `DO_NOT_STRIP=1` to the `make` command lines when you build the TDX firmware. I've added it to the README: https://github.com/microsoft/Cornelius/pull/11. Closing as fixed, thanks

**Comment by hw0505** [comment]
> You must pass `DO_NOT_STRIP=1` to the `make` command lines when you build the TDX firmware. I've added it to the README: [#11](https://github.com/microsoft/Cornelius/pull/11). Closing as fixed, thanks

When compiling the P-SEAMLDR and TDX module, I added `DO_NOT_STRIP=1` to the make command line, but the same issue still occurred.
