### ISSUE TITLE
MapGpa Failed with GPA_WITHOUT_HKID(Gpa + Size) >= Vm->LastPa

### ISSUE THREAD

**Issue by scottconstable** [microsoft/Cornelius#4]
I followed all of the instructions to build the TDX module (with Cornelius patches), P-SEAMLDR (with the Cornelius patch), and Cornelius. When I try to run the test program I see the following error message:

```
> .\Test.exe pseamldr.so.consts pseamldr.so libtdx.so
[+] Creating the Cornelius VM
[!] MapGpa Failed with GPA_WITHOUT_HKID(Gpa + Size) >= Vm->LastPa
```

I added some debugging code to reveal the values of `Gpa`, `Size`, and `Vm->LastPa` that are causing the crash:

```
[!] MapGpa failed with Gpa=0x8001000 Size=0x20000000, Vm->LastPa=0x28001000
```

One potential root cause is that the newest publicly available SEAMLDR source code that I was able to find is [1.5.00](https://www.intel.com/content/www/us/en/download/738874/intel-trust-domain-extension-intel-tdx-loader.html), but it appears that Cornelius was tested on a newer version, 1.5.01.02: https://github.com/microsoft/Cornelius/blob/main/TdxPatches/p-seamldr__1.5.01.02.diff.

I was able to find a version of the TDX module that matches the version used by Cornelius: https://github.com/intel/tdx-module/tree/TDX_1.5.01.

**Comment by JohnMcSandwich** [comment]
Thanks, that was a sanity check that was being too strict. Didn't notice earlier because we're using _sanitizer_ builds and on these the check doesn't fail. Fixed in: https://github.com/microsoft/Cornelius/pull/6.
