### ISSUE TITLE
Unrecognized CPUID leaf 0x5

### ISSUE THREAD

**Issue by scottconstable** [microsoft/Cornelius#7]
Hello,

I followed all of the instructions to build the TDX module (with Cornelius patches), P-SEAMLDR (with the Cornelius patch), and Cornelius. When I try to run the test program I see the following error message:

```
> .\Test.exe pseamldr.so.consts pseamldr.so libtdx.so
[+] Creating the Cornelius VM
[+] Executing PSEAMLDR.INSTALL on VCPU0
[+] Executing PSEAMLDR.INSTALL on VCPU1
[+] Executing PSEAMLDR.INSTALL on VCPU2
[+] Executing PSEAMLDR.INSTALL on VCPU3
[+] Executing TDH.SYS.INIT
[!][VCPU0] Unrecognized CPUID leaf 0x5 at RIP = 0xfffff96c0001e6bd
[!][VCPU0] Emulation error, RIP=fffff96c0001e6bd, callstack:
[!][VCPU0] > 0xfffff96c0001b1d7
[!][VCPU0] > 0xfffff96c00038f19
```

I'm using the SEAMLDR 1.5.00 and TDX Module 1.5.01.

**Comment by scottconstable** [comment]
My SDM tells me that 0x5 is the MONITOR/MWAIT leaf. It looks like this leaf has not been implemented in Cornelius. The location between case 0x4 and case 0x6 is here: https://github.com/microsoft/Cornelius/blob/5c35fb731778aa5e36fac575a5e0914b39f8f493/Lib/emulator.c#L664.

**Comment by scottconstable** [comment]
I created https://github.com/microsoft/Cornelius/pull/8 to fix this issue.

**Comment by JohnMcSandwich** [comment]
Thank you, I made a pass to support TDX Module version 1.5.05 (the latest): https://github.com/microsoft/Cornelius/pull/9. That should provide support for version 1.5.01 that you're using.

**Comment by scottconstable** [comment]
Thanks @JohnMcSandwich, I am now able to build TDX Module 1.5.05 with the latest PR.
